### ISSUE TITLE
Can the docker container load the OpenAPI YAML specification from a local file

### ISSUE THREAD

**Issue by dragonjuggler** [muonsoft/openapi-mock#50]
Hi.

It looks like the docker version of this requires specifying a URL to load the YAML specification.  I know that the container will not have access to a local file on the host, but has any method been looked into that would allow that?  For example, having a configuration service or admin service for the docker container which would allow "setting" the specification via a browser?

The docker version is more desirable, since nothing really needs to be installed, but serving up a YAML spec from a web service is not desirable (during development, the file will only be local).

Thanks.

-Mark

**Comment by strider2038** [comment]
Hello, @dragonjuggler !

You can use valid file path instead of web URL. To share your local config file with the running container you have to use docker volume. See example of docker-compose config below.

```yaml
version: '3.0'

services:
  openapi_mock:
    container_name: openapi_mock
    image: muonsoft/openapi-mock
    environment:
      OPENAPI_MOCK_SPECIFICATION_URL: '/app/petstore.yaml'
    volumes:
      - ./examples/petstore.yaml:/app/petstore.yaml
    ports:
      - "8080:8080"
```
