### ISSUE TITLE
Feature request: Watch mode

### ISSUE THREAD

**Issue by JoelVenable** [muonsoft/openapi-mock#65]
So I have my docker compose file as such...

```
services:
  mock-api:
    container_name: openapi_mock
    image: muonsoft/openapi-mock
    volumes:
      - ./schema:/schema
    environment:
      OPENAPI_MOCK_SPECIFICATION_URL: '/schema/schema.json'
    ports:
      - '3333:8080'
```

Is it possible for the container to watch for file changes if the url is a local file?  This would greatly help as we use this container in the dev cycle.
