### ISSUE TITLE
Wrong Documentation

### ISSUE THREAD

**Issue by razvangvr** [muonsoft/openapi-mock#85]
Please note that this part of the documentation is wrong/incomplete (and I wasted 2hours trying to get it to work)

> Also, you can use [Docker Compose](https://docs.docker.com/compose/). Example of docker-compose.yml
```
version: '3.0'

services:
  openapi_mock:
    container_name: openapi_mock
    image: muonsoft/openapi-mock
    environment:
      OPENAPI_MOCK_SPECIFICATION_URL: 'https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml'
    ports:
      - "8080:8080"
```
__
> Examples

```
https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml loads a file from a URL.
path/to/your/openapi-specification.yaml loads a file relative to working directory.
./path/to/your/openapi-specification.yaml loads a file relative to configuration file.
/path/to/your/openapi-specification.yaml loads a file by absolute path.
```

### Correct Documentation for docker compose, if you want to load the OpenApi `.yaml` file from local
If you want to reference a local file in docker compose
-  you must first mount the host dir into container`- ./swagger:/etc/swagger` 
- only then can you reference it
```
version: '3.0'

services:
  openapi_mock:
    container_name: openapi_mock
    image: muonsoft/openapi-mock
    volumes:
      - ./swagger:/etc/swagger
    environment:
      OPENAPI_MOCK_SPECIFICATION_URL: '/etc/swagger/studentapi.yaml'
    ports:
      - "8009:8080"
```

So it would help people if you can add in `docker-compose` documentation also an example with a `.yaml` file from local machine
